package org.kobjects.css;

public enum CssEnum {
  ERROR,

  AUTO, AQUA,
  BLACK, BLOCK, BOTH, BOTTOM, BLUE,
  CENTER, CIRCLE,
  DECIMAL, DISC,
  FIXED, FUCHSIA,
  GRAY, GREEN,
  INHERIT, INLINE, INLINE_BLOCK, INSIDE, ITALIC,
  LEFT, LIME, LIST_ITEM,
  MAROON, MEDIUM,
  NAVY, NONE, NO_REPEAT,
  OLIVE, OUTSIDE,
  PRE, PURPLE,
  RED, REPEAT, REPEAT_Y, REPEAT_X, RIGHT,
  SCROLL, SILVER, SOLID, SQUARE, STATIC, SUPER, SUB,
  TABLE, TABLE_CELL, TABLE_ROW, TEAL, THIN, THICK, TOP,
  UNDERLINE,
  WHITE,
  YELLOW, LINE_THROUGH, RELATIVE, ABSOLUTE;
}
